### ISSUE TITLE
Don't get the response

### ISSUE THREAD

**Issue by meaz** [Ajnasz/hubot-respond#1]
hubot-respond works fine for creating a new respond. However, when the word is given by a user, it doesn't respond.

How could I check what is going on and fix that eventually?

**Comment by Ajnasz** [comment]
Looks like things has changed since the last time I touched the code, the tests are breaking, I will need some time to fix it.

However if you have time and you want you can clone out the source and run the tests by executing `npm test` command.

**Comment by Ajnasz** [comment]
I think I found the issue, check the latest version (v1.0.7).

**Comment by meaz** [comment]
That was quick! THanks a lot, it works like a charm!
