### ISSUE TITLE
[Feature]  Mention user

### ISSUE THREAD

**Issue by meaz** [Ajnasz/hubot-respond#3]
If would be great if hubot could mention the user that worte the triggering word:

david : hubot respond to good morning with hello
hubot : Respond added
david : good morning
hubot : hello david (or hubot : david hello)

**Comment by Ajnasz** [comment]
That should be done in 1.1.0

To include sender name into message use `{sender}` in respond.
You can also include the room name if you want `{room}`

```
hubot respond to Hi with Welcome @{sender} in {room}
```

**Comment by meaz** [comment]
I've just tested, it doesn't work. It answers "Welcome @{sender}" but not "Welcome david"

**Comment by Ajnasz** [comment]
Are you sure you upgraded the package?

I tried on IRC and in the hubot shell, also tests are passing.

**Comment by meaz** [comment]
I have package 1.0.8
It is on a xmpp server, so could this be related?

**Comment by Ajnasz** [comment]
Yes, there is a new version of the package, 1.1.0 where this feature is
available, please upgrade!

XMPP should not matter
